global:
  resolve_timeout: 5m
  
route:
  receiver: 'slak'

          
receivers:
- name: 'slak'
  slak_configs:
    - channel: '#flask-app'
    - api_url: 'https://hooks.slack.com/services/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'
    
