apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-db
  labels:
    app: flask-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db
    spec:
      containers:
      - name: db
        image: ec2-3-91-3-153.compute-1.amazonaws.com/db:latest
#        ports:
#        - containerPort: 5000
        imagePullPolicy: IfNotPresent
#      imagePullSecrets:
#      - name: regcred
