---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask-db
spec:
  clusterIP: None
  selector:
    app: flask-db
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-db
spec:
  replicas: 3
  serviceName: flask-db
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: IMAGE-ADDR/db:IMAGE-NUMBER
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: efs-pvc
          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05fed4f448b82a8a1

