---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask-db
spec:
  clusterIP: None
  selector:
    app: flask-db
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-db
spec:
  replicas: 3
  serviceName: flask-db
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: IMAGE-ADDR/db:IMAGE-NUMBER
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumes:
  - name: data
    hostPath: 
        path: /mnt/pv1
