apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-monitor
  labels:
    app: app-monitor
spec:
  selector:
    matchLabels:
      app: app-monitor
  template:
    metadata:
      labels:
        app: app-monitor
    spec:
      containers:
      - name: monitoring-cadvisor
        image: google/cadvisor
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
        - name: run
          mountPath: /var/run
        - name: sys
          mountPath: /sys
        - name: docker
          mountPath: /var/lib/docker
             
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: run
        hostPath: 
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
           
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  labels:
    app: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      containers:
      - name: monitoring-nodeexporter
        image: prom/node-exporter
        ports:
          - containerPort: 9100
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
           
---

apiVersion: v1
kind: Service
metadata:
  name: cadvisor
spec:
  clusterIP: None
  selector:
    app: app-monitor
  ports:
    - port: 8081
      targetPort: 8080
      
---

apiVersion: v1
kind: Service
metadata:
  name: nodexporter
spec:
  clusterIP: None
  selector:
    app: node-monitor
  ports:
    - port: 9100
      targetPort: 9100
  
