apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ${regAddr}/app:${BUILD_NUMBER}
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
#      imagePullSecrets:
#      - name: regcred
---
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      nodePort: 32000
