apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-db
  labels:
    app: flask-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db
    spec:
      containers:
      - name: db
        image: IMAGE-ADDR/db:IMAGE-NUMBER
#        ports:
#        - containerPort: 5000
        imagePullPolicy: Always
#      imagePullSecrets:
#      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: svc-flask-db
spec:
  clusterIP: None
  selector:
    app: flask-db
  ports:
    - port: 3306
      targetPort: 3306

    
