apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: api
        image: IMAGE-ADDR/api:IMAGE-NUMBER
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
