version: '3.9'
services:
    prometheus:
#        container_name: monitoring-prometheus
        image: prom/prometheus
        ports: 
            - '9090:9090'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./alert.rules:/etc/prometheus/lert.rules
        networks:
            - monitoring-net
               
    grafana:
#        container_name: monitoring-grafana
        image: grafana/grafana
        volumes:
            - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
            - ./grafana-dash.json:/etc/grafana/provisioning/dashboards/grafana-dash.json
            - ./mysql-dash.json:/etc/grafana/provisioning/dashboards/mysql-dash.json
        ports:
            - '3000:3000'
        networks:
            - monitoring-net
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=123@qwer
            
#    alertmanager:
#        image: prom/alertmanager
#        volumes:
#            - ./alertmanager/:/etc/alertmanager/
#        ports:
#            - '9093:9093'
#        networks:
#            - monitoring-net
#        environment:
#            - GF_SECURITY_ADMIN_PASSWORD=123@qwer

networks:
    monitoring-net:
        driver: overlay
        attachable: true
