version: '3'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    image: kibana
    container_name: kibana
    ports:
      - '80:5601'
