version: '3.9'
services:
    prometheus:
#        container_name: monitoring-prometheus
        image: prom/prometheus
        ports: 
            - '9090:9090'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - monitoring-net
               
    grafana:
#        container_name: monitoring-grafana
        image: grafana/grafana
        volumes:
            - /var/lib/jenkins/workspace/Monitoring-stack/datasource.yml:/etc/grafana/provisioning/datasource/datasource.yml
            - /var/lib/jenkins/workspace/Monitoring-stack/dashbaord.yml:/etc/grafana/provisioning/dashboards/dashbaord.yml
            - /var/lib/jenkins/workspace/Monitoring-stack/grafana-dash.json:/etc/grafana/provisioning/dashboards/grafana-dash.json
        ports:
            - '3000:3000'
        networks:
            - monitoring-net

networks:
    monitoring-net:
        driver: overlay
        attachable: true
