version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'

  kibana:
    image: kibana:8.1.2
    container_name: kibana
    ports:
      - '80:5601'
