version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
      - 'ELASTIC_USERNAME=elasticadmin'
      - 'ELASTIC_PASSWORD=123@qwer'
    ports:
      - '9200:9200'

  kibana:
    image: kibana:8.1.2
    container_name: kibana
    ports:
      - '80:5601'
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - 'ELASTICSEARCH_HOSTS=http://ek_elasticsearch:9200'
      - 'KIBANA_PASSWORD=123@qwer'
      - 'ELASTICSEARCH_USERNAME=elasticadmin'
      - 'ELASTICSEARCH_PASSWORD=123@qwer'
