version: '3.9'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch:8.1.2
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'

  kibana:
    image: kibana
    container_name: kibana:8.1.2
    ports:
      - '80:5601'
