global:

  scrape_interval: 15s

  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'

    static_configs:

    - targets: ['${MONITOR_PUB_IP}:9090']

      labels:

        alias: 'prometheus'

  - job_name: 'cadvisor'

    static_configs:

    - targets: ['${SLAVE_PRV_IP}:8080']

      labels:

        alias: 'cadvisor'

  - job_name: 'node-exporter'

    static_configs:

    - targets: ['${SLAVE_PRV_IP}:9100']

      labels:

        alias: 'node-exporter'
