kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  type: NodePort
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  ports:
    protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 32010
